### ISSUE TITLE
PNG files form jquery-ui.min.css are missing

### ISSUE THREAD

**Issue by Zodiac1978** [barryceelen/datepicker3000#1]
The png files linked in https://github.com/barryceelen/datepicker3000/blob/master/css/jquery-ui.min.css are missing. For example /images/ui-bg_flat_75_ffffff_40x100.png

BTW Thank you for creating this test plugin and for fixing my ticket :)

**Comment by barryceelen** [comment]
Ok, thanks, fixed!
